name: Python Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Run flake8 linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install flake8
        run: pip install flake8

      - name: Run flake8
        run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
